[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "django_vite_plugin"
version = "4.1.1_dev"
authors = [
  { name="Stepan", email="" },
]
description = "Vite build tools integration for django"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/B2-V/django-vite-plugin/"
"Bug Tracker" = "https://github.com/B2-V/django-vite-plugin//issues"
